In [1]:
import pandas as pd
import pandas.io.sql as psql
import os
import sys
from datetime import date
current_date = date.today()
#%load_ext autotime
import re
import csv
import pandas as pd
import numpy as np
import os
from glob import glob
from tqdm import tqdm
import matplotlib.pyplot as plt
#from matplotlib_venn import venn2, venn3
import warnings
import time
import datetime as dt
import itertools
from more_itertools import unique_everseen
warnings.filterwarnings("ignore")
#import pandasql as ps
import seaborn as sns
import json
from ast import literal_eval
import ast

In [2]:
# STEPS to get data

# get arr of notes
# get arr of keywords
# split note in arr
# for each word in keyword list, get count of it in arr (word_list.count(curr_keyword))
# also store which keywords are matched in arr
# have df (with cols patient id, encounter id, note TXT, keyword count, list of flagged keywords)
# to get # of general encouters --> do len(df[df["keyword_count"] >= 1])
# to get # of such encounters per patient
    # get list of unique patient ids
    # for each one, do len(df[df["patient_id"] == curr_patient_id]["encounter_id"])
    
# REPRESENTING data

# exported dataframe to csv with cols patient_id, num encounters keywords >= 1
# exported dataframe to csv that has general encounters where keywords >= 1, cols: patient id, encounter id, note txt, keyword count, matched keywords
# Summary Statistics: number of encounters with keywords >= 1, number of average encounters per patient with such encounters

In [3]:
df1 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Mayuresh\APOE33\apoe33_notes_1.csv")
#df2 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Mayuresh\APOE33\apoe33_notes_2.csv")
# df3 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Mayuresh\APOE33\apoe33_notes_3.csv")
# df4 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Mayuresh\APOE33\apoe33_notes_4.csv")
# df5 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Mayuresh\APOE33\apoe33_notes_5.csv")

In [4]:
#frames = [df1, df2]
notes = df1

In [5]:
notes["NoteTXT"] = notes["NoteTXT"].str.replace('\s+', ' ', regex=True)
notes['NoteTXT'] = '-------------------------------------------------------------------------------------------------------------' + notes['NoteTXT'].astype(str)+'-------------------------------------------------------------------------------------------------------------'

In [6]:
regex = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\Sentence-Analysis\EDA\Getting_Data\keywords.csv")

In [7]:
regex

                     REGEX
0                 dementia
1                cognition
2                   memory
3                      CDR
4                     MMSE
5                     MOCA
6                Alzheimer
7   cognitive\s*impairment
8                      MCI
9               cerebellar
10          Neurocognitive
11                    lewy
12                  pick's
13                Cortical
14            Corticobasal
15                cerebral
16         cerebrovascular
17                 amnesia

In [8]:
notes

,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,InpatientNoteTypeDSC,buckets,NoteCSNID,LineNBR,NoteTXT
0,100000272,10040002098,Z6352398,3.048340e+09,1999-11-17 00:00:00.0000000,System Generated,330550893,Op Note,1,3.164291e+08,1.0,----------------------------------------------...
1,100000272,10040002098,Z6352398,3.052785e+09,2009-03-15 00:00:00.0000000,System Generated,337968894,Discharge Summary,1,3.236400e+08,1.0,----------------------------------------------...
2,100000272,10040002098,Z6352398,3.056972e+09,2001-02-19 00:00:00.0000000,System Generated,353890517,Discharge Summary,1,3.393630e+08,1.0,----------------------------------------------...
3,100000272,10040002098,Z6352398,3.076013e+09,2015-06-12 00:00:00.0000000,Office Visit,464327283,MR AVS Snapshot,1,4.466111e+08,1.0,----------------------------------------------...
4,100000272,10040002098,Z6352398,3.076013e+09,2015-06-12 00:00:00.0000000,Office Visit,464415371,Progress Notes,1,4.466893e+08,1.0,----------------------------------------------...
...,...,...,...,...,...,...,...,...,...,...,...,...
1079066,100365175,10059358563,Z8714148,3.375703e+09,2021-05-26 00:00:00.0000000,Patient Message,5878295268,Telephone Encounter,1,5.876515e+09,1.0,----------------------------------------------...
1079067,100365175,10059358563,Z8714148,3.378998e+09,2021-06-14 00:00:00.0000000,Letter (Out),5966394734,Letter,1,5.965382e+09,1.0,----------------------------------------------...
1079068,100365175,10059358563,Z8714148,3.379970e+09,2021-06-17 00:00:00.0000000,Patient Message,5994021567,Telephone Encounter,1,5.993225e+09,1.0,----------------------------------------------...
1079069,100365175,10059358563,Z8714148,3.381402e+09,2021-06-23 00:00:00.0000000,Refill,6016856527,Telephone Encounter,1,6.016268e+09,1.0,----------------------------------------------...
1079070,100365175,10059358563,Z8714148,3.381402e+09,2021-06-23 00:00:00.0000000,Refill,6017563767,Telephone Encounter,1,6.016979e+09,1.0,----------------------------------------------...

In [9]:
locations = []
for r in tqdm(notes['NoteTXT']):
    try:
        locations.append([match.span() \
                  for match in re.finditer(re.compile("|".join(regex["REGEX"]), 
                                                  re.IGNORECASE),r)])
    except:
        locations.append([])

notes["regex_location"] = locations
notes.to_csv("apoe33_notes_1_w_locations.csv")

100%|██████████████████████████████████████████████████████████████████████| 1079071/1079071 [14:05<00:00, 1276.68it/s]

In [10]:
notes.head(100)

,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,InpatientNoteTypeDSC,buckets,NoteCSNID,LineNBR,NoteTXT,regex_location
0,100000272,10040002098,Z6352398,3.048340e+09,1999-11-17 00:00:00.0000000,System Generated,330550893,Op Note,1,3.164291e+08,1.0,----------------------------------------------...,[]
1,100000272,10040002098,Z6352398,3.052785e+09,2009-03-15 00:00:00.0000000,System Generated,337968894,Discharge Summary,1,3.236400e+08,1.0,----------------------------------------------...,[]
2,100000272,10040002098,Z6352398,3.056972e+09,2001-02-19 00:00:00.0000000,System Generated,353890517,Discharge Summary,1,3.393630e+08,1.0,----------------------------------------------...,[]
3,100000272,10040002098,Z6352398,3.076013e+09,2015-06-12 00:00:00.0000000,Office Visit,464327283,MR AVS Snapshot,1,4.466111e+08,1.0,----------------------------------------------...,[]
4,100000272,10040002098,Z6352398,3.076013e+09,2015-06-12 00:00:00.0000000,Office Visit,464415371,Progress Notes,1,4.466893e+08,1.0,----------------------------------------------...,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562580628,ED Triage Notes,1,1.508448e+09,1.0,----------------------------------------------...,[]
96,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562613299,ED Provider Notes,1,1.508556e+09,1.0,----------------------------------------------...,"[(3947, 3950)]"
97,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562623720,ED Notes,1,1.508494e+09,1.0,----------------------------------------------...,[]
98,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562660243,ED Provider Notes,1,1.508533e+09,1.0,----------------------------------------------...,[]
99,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562661040,ED Provider Notes,1,1.509329e+09,1.0,----------------------------------------------...,[]

In [ ]:
print("test")

In [11]:
l = []
for i in tqdm(range(len(notes["regex_location"]))):
    s = []
    try:
        for j in notes["regex_location"][i]:
            s.append(notes["NoteTXT"][i][j[0]-100 : j[0]+100])
    except:
        pass
    l.append(s)
    
    
notes["regex_sent"] = l

100%|█████████████████████████████████████████████████████████████████████| 1079071/1079071 [00:50<00:00, 21273.74it/s]

In [14]:
notes.to_csv("apoe33_notes_1_w_locations_and_sequences.csv")

In [15]:
notes.head(100)

,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,InpatientNoteTypeDSC,buckets,NoteCSNID,LineNBR,NoteTXT,regex_location,regex_sent
0,100000272,10040002098,Z6352398,3.048340e+09,1999-11-17 00:00:00.0000000,System Generated,330550893,Op Note,1,3.164291e+08,1.0,----------------------------------------------...,[],[]
1,100000272,10040002098,Z6352398,3.052785e+09,2009-03-15 00:00:00.0000000,System Generated,337968894,Discharge Summary,1,3.236400e+08,1.0,----------------------------------------------...,[],[]
2,100000272,10040002098,Z6352398,3.056972e+09,2001-02-19 00:00:00.0000000,System Generated,353890517,Discharge Summary,1,3.393630e+08,1.0,----------------------------------------------...,[],[]
3,100000272,10040002098,Z6352398,3.076013e+09,2015-06-12 00:00:00.0000000,Office Visit,464327283,MR AVS Snapshot,1,4.466111e+08,1.0,----------------------------------------------...,[],[]
4,100000272,10040002098,Z6352398,3.076013e+09,2015-06-12 00:00:00.0000000,Office Visit,464415371,Progress Notes,1,4.466893e+08,1.0,----------------------------------------------...,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562580628,ED Triage Notes,1,1.508448e+09,1.0,----------------------------------------------...,[],[]
96,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562613299,ED Provider Notes,1,1.508556e+09,1.0,----------------------------------------------...,"[(3947, 3950)]",[cular: Normal rate. Pulmonary/Chest: Effort n...
97,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562623720,ED Notes,1,1.508494e+09,1.0,----------------------------------------------...,[],[]
98,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562660243,ED Provider Notes,1,1.508533e+09,1.0,----------------------------------------------...,[],[]
99,100000272,10040002098,Z6352398,3.161459e+09,2017-06-23 00:00:00.0000000,Hospital Encounter,1562661040,ED Provider Notes,1,1.509329e+09,1.0,----------------------------------------------...,[],[]

In [ ]:
notes['regex_sent'] = notes['regex_sent'].astype(str)
notes['regex_sent'] = notes['regex_sent'].str.replace('[', '')
notes['regex_sent'] = notes['regex_sent'].str.replace(']', '')
notes = notes.replace(r'^\s*$', np.NaN, regex=True)