In [1]:
import pandas as pd
import pandas.io.sql as psql
import os
import sys
from datetime import date
current_date = date.today()
#%load_ext autotime
import re
import csv
import pandas as pd
import numpy as np
import os
from glob import glob
from tqdm import tqdm
import matplotlib.pyplot as plt
#from matplotlib_venn import venn2, venn3
import warnings
import time
import datetime as dt
import itertools
from more_itertools import unique_everseen
warnings.filterwarnings("ignore")
#import pandasql as ps
import seaborn as sns
import json
from ast import literal_eval
import ast
from fuzzywuzzy import process
from nltk.corpus import words

## Getting Encounter quantities per patient and in general

In [2]:
e = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\padded_matches_7_14.csv")
n = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\not_padded_matches_7_14.csv")

In [64]:
e = e.drop(columns = ['Unnamed: 0.1.1.1.1'], axis = 1) #only run if runtime reset

In [3]:
e.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1',
       'Unnamed: 0.1.1.1.1', 'EMPI', 'MRN', 'PatientID', 'PatientEncounterID',
       'ContactDTS', 'EncounterTypeDSC', 'NoteID', 'InpatientNoteTypeDSC',
       'buckets', 'NoteCSNID', 'LineNBR', 'NoteTXT', 'regex_location',
       'regex_sent', 'regex_match', 'match_count', 'pruned_regex_location',
       'merged_row_location', 'merged_regex_sent', 'merged_regex_match',
       'padded_merged_row_location', 'padded_merged_regex_sent',
       'padded_char_count', 'note_char_count'],
      dtype='object')

In [67]:
n["sequence_level_regex_match"] = n["merged_regex_sent"].to_list()

In [69]:
n.columns = e.columns

In [70]:
df = pd.concat([e, n])

In [71]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,...,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match,padded_merged_row_location,padded_merged_regex_sent,padded_char_count,note_char_count
0,0,0,0,0.0,100000272,10040002098,Z6352398,3.076070e+09,2015-06-17 00:00:00.0000000,Office Visit,...,['cerebral'],1,"[(100, 109)]","[(5750, 5958)]",------- ncer. She passed secondary to this. He...,[' cerebral'],"(5457, 6251)",ked at HMS in the department of psychobiology ...,794,19217.0
1,1,1,1,1.0,100000272,10040002098,Z6352398,3.076214e+09,2015-07-16 00:00:00.0000000,Office Visit,...,['memory'],1,"[(100, 107)]","[(3543, 3749)]",------- a. Skin: No rashes or lesions. Neurolo...,[' memory'],"(3248, 4044)",or lymphadenopathy. Chest: Clear to auscultati...,796,5850.0
2,2,2,2,14.0,100000272,10040002098,Z6352398,3.242118e+09,2019-03-14 00:00:00.0000000,Office Visit,...,['dementia'],1,"[(100, 109)]","[(8641, 8849)]","------- ractures, obesity, insulin resistance,...",[' dementia'],"(8345, 9145)",ession alone in the meta-analysis. We discusse...,800,13298.0
3,3,3,3,15.0,100000272,10040002098,Z6352398,3.322836e+09,2020-12-04 00:00:00.0000000,Telemedicine - audio only,...,['MOCA'],1,"[(100, 105)]","[(948, 1152), (4778, 4987), (5004, 5331)]",------- accept for this week when he ran out ...,"[' moca', ' cognition', ' memory']","[(930, 1152), (4778, 4987), (5004, 5349)]",------- ing tylenol really accept for this we...,803,8711.0
4,4,4,4,20.0,100000272,10040002098,Z6352398,3.325561e+09,2020-09-18 00:00:00.0000000,Telemedicine - audio only,...,['cognition'],1,"[(100, 110)]","[(5367, 5576), (5593, 5812)]",------- ue Tylenol 1g q8 as needed - If pain w...,"[' cognition', ' memory']","[(5188, 5576), (5593, 5991)]",------- in is related to cancer. Reassuringly...,804,9145.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40300,60817,60817,277874,NaN,113705759,10127549029,Z16320629,3.285425e+09,2020-04-28 00:00:00.0000000,Telemedicine - audio only,...,"[""memory""]",1,"[(97, 104)]","[(1346, 1552), (1603, 1809), (5360, 5569), (59...","------- se ""she took a break"" and wants to dis...","[' memory', ' cognition', ' cerebral', ' cereb...","[(538, 547), (1626, 1635), (1844, 1853), (108,...","------- se ""she took a break"" and wants to dis...",1949,11314.0
40301,60818,60818,277883,NaN,113705759,10127549029,Z16320629,3.305416e+09,2020-09-22 00:00:00.0000000,Telemedicine - audio only,...,"[""memory""]",1,"[(99, 106)]","[(1165, 1371), (4255, 4464), (4876, 5084), (56...","------- all of her medications, including asp...","[' memory', ' cognition', ' cerebral', ' cereb...","[(323, 332), (1411, 1420), (1629, 1638), (108,...","------- all of her medications, including asp...",1734,10113.0
40302,60819,60819,277896,NaN,113705759,10127549029,Z16320629,3.327430e+09,2021-01-25 00:00:00.0000000,Telemedicine,...,"[""cognition""]",1,"[(98, 108)]","[(194, 403), (444, 653), (1326, 1532), (4453, ...","------- ? Patient, Chart, daughter Olga Mode o...","[' cognition', ' cerebral', ' memory', ' cereb...","[(2816, 2824), (108, 117), (326, 335), (974, 9...","------- ? Patient, Chart, daughter Olga Mode o...",3009,12320.0
40303,60820,60820,277912,NaN,113705759,10127549029,Z16320629,3.349755e+09,2021-04-20 00:00:00.0000000,Telemedicine,...,"[""cognition""]",1,"[(98, 108)]","[(202, 411), (452, 661), (3626, 3875), (4946, ...","------- ? Patient, Chart, daughter Olga Mode o...","[' cognition', ' cerebral', ' cognitive impair...","[(2103, 2111), (108, 117), (326, 335), (544, 5...","------- ? Patient, Chart, daughter Olga Mode o...",2835,11250.0
40304,60834,60834,277961,NaN,113708529,10127577079,Z16323433,3.196619e+09,2018-04-16 00:00:00.0000000,Office Visit,...,"[""Cognition""]",1,"[(98, 108)]","[(239, 442), (964, 1167), (4227, 4436), (5937,...","------- h muscle invasive bladder cancer, curr...",[' cognition'],"[(532, 541)]","------- h muscle invasive bladder cancer, curr...",1112,7027.0

In [72]:
speciality = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Mayuresh\APOE33\specialty_visit_encounters.csv")
pcp = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Mayuresh\APOE33\pcp_visit_encounters.csv")

In [73]:
df = pd.merge(df, pcp, left_on = 'PatientEncounterID', right_on = 'PatientEncounterID', how = 'left')

In [74]:
df = pd.merge(df, speciality, left_on = 'PatientEncounterID', right_on = 'PatientEncounterID', how = 'left')

In [75]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,...,merged_regex_sent,merged_regex_match,padded_merged_row_location,padded_merged_regex_sent,padded_char_count,note_char_count,PCPID,EncounterEpicProviderID,pcp_flag,SpecialtyDSC
0,0,0,0,0.0,100000272,10040002098,Z6352398,3.076070e+09,2015-06-17 00:00:00.0000000,Office Visit,...,------- ncer. She passed secondary to this. He...,[' cerebral'],"(5457, 6251)",ked at HMS in the department of psychobiology ...,794,19217.0,NaN,1521494,0,NaN
1,1,1,1,1.0,100000272,10040002098,Z6352398,3.076214e+09,2015-07-16 00:00:00.0000000,Office Visit,...,------- a. Skin: No rashes or lesions. Neurolo...,[' memory'],"(3248, 4044)",or lymphadenopathy. Chest: Clear to auscultati...,796,5850.0,NaN,1012865,0,NaN
2,2,2,2,14.0,100000272,10040002098,Z6352398,3.242118e+09,2019-03-14 00:00:00.0000000,Office Visit,...,"------- ractures, obesity, insulin resistance,...",[' dementia'],"(8345, 9145)",ession alone in the meta-analysis. We discusse...,800,13298.0,1002888.0,1668416,0,NaN
3,3,3,3,15.0,100000272,10040002098,Z6352398,3.322836e+09,2020-12-04 00:00:00.0000000,Telemedicine - audio only,...,------- accept for this week when he ran out ...,"[' moca', ' cognition', ' memory']","[(930, 1152), (4778, 4987), (5004, 5349)]",------- ing tylenol really accept for this we...,803,8711.0,1002888.0,1746848,0,NaN
4,4,4,4,20.0,100000272,10040002098,Z6352398,3.325561e+09,2020-09-18 00:00:00.0000000,Telemedicine - audio only,...,------- ue Tylenol 1g q8 as needed - If pain w...,"[' cognition', ' memory']","[(5188, 5576), (5593, 5991)]",------- in is related to cancer. Reassuringly...,804,9145.0,1002888.0,1746848,0,NaN

In [89]:
len(df["PatientID"].unique())

16428

In [103]:
df_clone = df.drop_duplicates(subset='PatientEncounterID', keep="first")

In [155]:
len(df["PatientEncounterID"].unique())

178994

In [104]:
encounter_counts = df_clone.groupby(["EMPI"])['PatientEncounterID'].count().reset_index()
encounter_counts

            EMPI  PatientEncounterID
0      100000272                   9
1      100000521                   6
2      100000623                   3
3      100000894                   5
4      100000920                   3
...          ...                 ...
16423  113714475                   2
16424  113716850                   4
16425  113722466                   5
16426  113722742                  11
16427  113727131                   1

[16428 rows x 2 columns]

In [106]:
encounter_counts["PatientEncounterID"].describe()

count    16428.000000
mean        10.895666
std         14.880333
min          1.000000
25%          2.000000
50%          6.000000
75%         13.000000
max        316.000000
Name: PatientEncounterID, dtype: float64

In [150]:
encounter_counts.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\encounter_counts.csv", index= False)

In [76]:
speciality_counts = df.groupby(["EMPI"])['SpecialtyDSC'].count().reset_index()

In [77]:
speciality_counts.head()

        EMPI  SpecialtyDSC
0  100000272             0
1  100000521             0
2  100000623             0
3  100000894             0
4  100000920             0

In [83]:
speciality_counts["SpecialtyDSC"].describe()

count    16428.000000
mean         1.673545
std          4.634825
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max         87.000000
Name: SpecialtyDSC, dtype: float64

In [88]:
speciality_counts["SpecialtyDSC"].median()

0.0

In [92]:
speciality_counts["SpecialtyDSC"].sum()

27493

In [78]:
pcp_counts = df[df["pcp_flag"] == 1].groupby(["EMPI"])["pcp_flag"].count().reset_index()

In [81]:
pcp_counts.head()

        EMPI  pcp_flag
0  100000521         1
1  100001150         3
2  100001521        14
3  100001768         8
4  100001873         3

In [84]:
pcp_counts["pcp_flag"].describe()

count    7587.000000
mean        5.251219
std         5.630849
min         1.000000
25%         2.000000
50%         4.000000
75%         6.000000
max        94.000000
Name: pcp_flag, dtype: float64

In [94]:
pcp_counts["pcp_flag"].median()

4.0

In [91]:
pcp_counts["pcp_flag"].sum()

39841

In [151]:
speciality_counts.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\speciality_counts.csv", index = False)

In [152]:
pcp_counts.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\pcp_counts.csv", index = False)

In [154]:
df.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\MASTER_7_14.csv")

## Recalculating Keyword Matches

In [111]:
unique_empi = df["PatientID"].unique().tolist()

In [112]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,...,merged_regex_sent,merged_regex_match,padded_merged_row_location,padded_merged_regex_sent,padded_char_count,note_char_count,PCPID,EncounterEpicProviderID,pcp_flag,SpecialtyDSC
0,0,0,0,0.0,100000272,10040002098,Z6352398,3.076070e+09,2015-06-17 00:00:00.0000000,Office Visit,...,------- ncer. She passed secondary to this. He...,[' cerebral'],"(5457, 6251)",ked at HMS in the department of psychobiology ...,794,19217.0,NaN,1521494,0,NaN
1,1,1,1,1.0,100000272,10040002098,Z6352398,3.076214e+09,2015-07-16 00:00:00.0000000,Office Visit,...,------- a. Skin: No rashes or lesions. Neurolo...,[' memory'],"(3248, 4044)",or lymphadenopathy. Chest: Clear to auscultati...,796,5850.0,NaN,1012865,0,NaN
2,2,2,2,14.0,100000272,10040002098,Z6352398,3.242118e+09,2019-03-14 00:00:00.0000000,Office Visit,...,"------- ractures, obesity, insulin resistance,...",[' dementia'],"(8345, 9145)",ession alone in the meta-analysis. We discusse...,800,13298.0,1002888.0,1668416,0,NaN
3,3,3,3,15.0,100000272,10040002098,Z6352398,3.322836e+09,2020-12-04 00:00:00.0000000,Telemedicine - audio only,...,------- accept for this week when he ran out ...,"[' moca', ' cognition', ' memory']","[(930, 1152), (4778, 4987), (5004, 5349)]",------- ing tylenol really accept for this we...,803,8711.0,1002888.0,1746848,0,NaN
4,4,4,4,20.0,100000272,10040002098,Z6352398,3.325561e+09,2020-09-18 00:00:00.0000000,Telemedicine - audio only,...,------- ue Tylenol 1g q8 as needed - If pain w...,"[' cognition', ' memory']","[(5188, 5576), (5593, 5991)]",------- in is related to cancer. Reassuringly...,804,9145.0,1002888.0,1746848,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279219,60817,60817,277874,NaN,113705759,10127549029,Z16320629,3.285425e+09,2020-04-28 00:00:00.0000000,Telemedicine - audio only,...,"------- se ""she took a break"" and wants to dis...","[' memory', ' cognition', ' cerebral', ' cereb...","[(538, 547), (1626, 1635), (1844, 1853), (108,...","------- se ""she took a break"" and wants to dis...",1949,11314.0,1007065.0,1558180,0,NaN
279220,60818,60818,277883,NaN,113705759,10127549029,Z16320629,3.305416e+09,2020-09-22 00:00:00.0000000,Telemedicine - audio only,...,"------- all of her medications, including asp...","[' memory', ' cognition', ' cerebral', ' cereb...","[(323, 332), (1411, 1420), (1629, 1638), (108,...","------- all of her medications, including asp...",1734,10113.0,1007065.0,1558180,0,NaN
279221,60819,60819,277896,NaN,113705759,10127549029,Z16320629,3.327430e+09,2021-01-25 00:00:00.0000000,Telemedicine,...,"------- ? Patient, Chart, daughter Olga Mode o...","[' cognition', ' cerebral', ' memory', ' cereb...","[(2816, 2824), (108, 117), (326, 335), (974, 9...","------- ? Patient, Chart, daughter Olga Mode o...",3009,12320.0,1007065.0,1558180,0,NaN
279222,60820,60820,277912,NaN,113705759,10127549029,Z16320629,3.349755e+09,2021-04-20 00:00:00.0000000,Telemedicine,...,"------- ? Patient, Chart, daughter Olga Mode o...","[' cognition', ' cerebral', ' cognitive impair...","[(2103, 2111), (108, 117), (326, 335), (544, 5...","------- ? Patient, Chart, daughter Olga Mode o...",2835,11250.0,1007065.0,1558180,0,NaN
279223,60834,60834,277961,NaN,113708529,10127577079,Z16323433,3.196619e+09,2018-04-16 00:00:00.0000000,Office Visit,...,"------- h muscle invasive bladder cancer, curr...",[' cognition'],"[(532, 541)]","------- h muscle invasive bladder cancer, curr...",1112,7027.0,1122712.0,1111086,0,NaN

In [115]:
regex = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\APOE-SLAT\EDA\Getting_Data\keywords.csv")

k = regex["REGEX"].to_list()
c = regex["CASE"].to_list()
p_list = []

for i in range(len(k)):
    if (c[i] == 0):
        p_list.append(re.compile(k[i][5:], re.IGNORECASE))
    elif (c[i] == 1):
        p_list.append(re.compile(k[i]))
print(p_list)

[re.compile('\\bdementia\\b', re.IGNORECASE), re.compile('\\bcognition\\b', re.IGNORECASE), re.compile('\\bmemory\\b', re.IGNORECASE), re.compile('\\bMMSE\\b', re.IGNORECASE), re.compile('\\bMOCA\\b', re.IGNORECASE), re.compile('\\bAlzheimer\\b', re.IGNORECASE), re.compile('\\bcognitive\\s*impairment\\b', re.IGNORECASE), re.compile('(?-i:)\\bMCI\\b'), re.compile('\\bcerebellar\\b', re.IGNORECASE), re.compile('\\bNeurocognitive\\b', re.IGNORECASE), re.compile('\\blewy\\b', re.IGNORECASE), re.compile("\\bpick's\\b", re.IGNORECASE), re.compile('\\bCorticobasal\\b', re.IGNORECASE), re.compile('\\bcerebral\\b', re.IGNORECASE), re.compile('\\bcerebrovascular\\b', re.IGNORECASE), re.compile('\\bamnesia\\b', re.IGNORECASE), re.compile('(?-i:)\\bAD\\b'), re.compile('(?-i:)\\bLBD\\b')]

In [116]:
l = []
for note in tqdm(df["padded_merged_regex_sent"]):
    curr = []
    for p in (p_list):
        m = list(set(re.findall(p, note)))
        m = list(set(map(str.lower, m)))
        if (m != []):
            curr.append("".join(m))
    #print(curr)
    #print(l)
    l.append(str(curr))

df["padded_regex_match"] = l

100%|████████████████████████████████████████████████████████████████████████| 279224/279224 [03:03<00:00, 1520.78it/s]

In [117]:
cols =  ['dementia', 'cognition', 'memory', 'mmse', 'moca', 'alzheimer', 'cognitive impairment', 'mci', 'cerebellar', 'neurocognitive', 'lewy', "pick's",  'corticobasal', 'cerebral', 'cerebrovascular', 'amnesia', 'ad', 'lbd']
len(cols)

18

In [118]:
summary_stats  = pd.DataFrame(pd.np.empty((len(unique_empi), len(cols))) * pd.np.nan) 
summary_stats.columns = cols

In [119]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,...,merged_regex_match,padded_merged_row_location,padded_merged_regex_sent,padded_char_count,note_char_count,PCPID,EncounterEpicProviderID,pcp_flag,SpecialtyDSC,padded_regex_match
0,0,0,0,0.0,100000272,10040002098,Z6352398,3.076070e+09,2015-06-17 00:00:00.0000000,Office Visit,...,[' cerebral'],"(5457, 6251)",ked at HMS in the department of psychobiology ...,794,19217.0,NaN,1521494,0,NaN,['cerebral']
1,1,1,1,1.0,100000272,10040002098,Z6352398,3.076214e+09,2015-07-16 00:00:00.0000000,Office Visit,...,[' memory'],"(3248, 4044)",or lymphadenopathy. Chest: Clear to auscultati...,796,5850.0,NaN,1012865,0,NaN,['memory']
2,2,2,2,14.0,100000272,10040002098,Z6352398,3.242118e+09,2019-03-14 00:00:00.0000000,Office Visit,...,[' dementia'],"(8345, 9145)",ession alone in the meta-analysis. We discusse...,800,13298.0,1002888.0,1668416,0,NaN,['dementia']
3,3,3,3,15.0,100000272,10040002098,Z6352398,3.322836e+09,2020-12-04 00:00:00.0000000,Telemedicine - audio only,...,"[' moca', ' cognition', ' memory']","[(930, 1152), (4778, 4987), (5004, 5349)]",------- ing tylenol really accept for this we...,803,8711.0,1002888.0,1746848,0,NaN,"['cognition', 'memory', 'moca']"
4,4,4,4,20.0,100000272,10040002098,Z6352398,3.325561e+09,2020-09-18 00:00:00.0000000,Telemedicine - audio only,...,"[' cognition', ' memory']","[(5188, 5576), (5593, 5991)]",------- in is related to cancer. Reassuringly...,804,9145.0,1002888.0,1746848,0,NaN,"['cognition', 'memory']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279219,60817,60817,277874,NaN,113705759,10127549029,Z16320629,3.285425e+09,2020-04-28 00:00:00.0000000,Telemedicine - audio only,...,"[' memory', ' cognition', ' cerebral', ' cereb...","[(538, 547), (1626, 1635), (1844, 1853), (108,...","------- se ""she took a break"" and wants to dis...",1949,11314.0,1007065.0,1558180,0,NaN,"['cognition', 'memory', 'cerebellar', 'cerebral']"
279220,60818,60818,277883,NaN,113705759,10127549029,Z16320629,3.305416e+09,2020-09-22 00:00:00.0000000,Telemedicine - audio only,...,"[' memory', ' cognition', ' cerebral', ' cereb...","[(323, 332), (1411, 1420), (1629, 1638), (108,...","------- all of her medications, including asp...",1734,10113.0,1007065.0,1558180,0,NaN,"['cognition', 'memory', 'cerebellar', 'cerebral']"
279221,60819,60819,277896,NaN,113705759,10127549029,Z16320629,3.327430e+09,2021-01-25 00:00:00.0000000,Telemedicine,...,"[' cognition', ' cerebral', ' memory', ' cereb...","[(2816, 2824), (108, 117), (326, 335), (974, 9...","------- ? Patient, Chart, daughter Olga Mode o...",3009,12320.0,1007065.0,1558180,0,NaN,"['dementia', 'cognition', 'memory', 'mci', 'ce..."
279222,60820,60820,277912,NaN,113705759,10127549029,Z16320629,3.349755e+09,2021-04-20 00:00:00.0000000,Telemedicine,...,"[' cognition', ' cerebral', ' cognitive impair...","[(2103, 2111), (108, 117), (326, 335), (544, 5...","------- ? Patient, Chart, daughter Olga Mode o...",2835,11250.0,1007065.0,1558180,0,NaN,"['dementia', 'cognition', 'moca', 'cognitive i..."
279223,60834,60834,277961,NaN,113708529,10127577079,Z16323433,3.196619e+09,2018-04-16 00:00:00.0000000,Office Visit,...,[' cognition'],"[(532, 541)]","------- h muscle invasive bladder cancer, curr...",1112,7027.0,1122712.0,1111086,0,NaN,['cognition']

In [120]:
for i in tqdm(range(len(unique_empi))):
    keyword_list = list((df[df['PatientID'] == unique_empi[i]]['padded_regex_match'].values))
    #print("KL: ", keyword_list)
    match_tuples = []
    for j in range(len(keyword_list)):
        sub = "\', \'"
        x = list(eval(keyword_list[j]))# [2:len(keyword_list[j])-2]
        #print("X: ", x)
#         if sub in x:
#             #print("YES")
#             x = x.split("\', \'")
#             #print("X2: ", x)
#         else:
#             x = x.split("\", \"")
        for z in range(len(x)):
            match_tuples.append((x[z], 0))
    #print("MT: ", match_tuples)

    freq = {"dementia":0
        ,"cognition":0
        ,"cognition":0
        ,"memory":0
        ,"mmse":0
        ,"moca":0
        ,"alzheimer":0
        ,'cognitive impairment':0
        ,"mci":0
        ,"cerebellar":0
        ,"neurocognitive":0
        ,"lewy":0
        ,"pick's":0
        ,"corticobasal":0
        ,"cerebral":0
        ,"cerebrovascular":0
        ,"amnesia":0
        ,"ad": 0
        ,"lbd": 0
    }

    for k, v in match_tuples:   
        if (k != ''):
            if (k == 'cognitive impairmentcognitiveimpairment'):
                k = 'cognitive impairment'
                freq.update({str(k.lower()):int(freq[k.lower()] + 1)})
            else:
                freq.update({str(k.lower()):int(freq[k.lower()] + 1)})
            
    #print(freq.items())
    #print(summary_stats["dementia"])
    for k, v in freq.items():
        #print(str(k.lower()))
        summary_stats[str(k.lower())][i] = int(v)

100%|████████████████████████████████████████████████████████████████████████████| 16428/16428 [09:40<00:00, 28.30it/s]

In [121]:
summary_stats

,dementia,cognition,memory,mmse,moca,alzheimer,cognitive impairment,mci,cerebellar,neurocognitive,lewy,pick's,corticobasal,cerebral,cerebrovascular,amnesia,ad,lbd
0,2.0,4.0,7.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
3,1.0,3.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16423,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16424,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16425,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
16426,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16427,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [122]:
summary_stats.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\summary_stats_7_14.csv")

In [123]:
summary_stats = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\summary_stats_7_14.csv")

In [125]:
summary_stats["Sum"].describe()

count    16429.000000
mean        26.218408
std         53.763780
min          1.000000
25%          3.000000
50%          9.000000
75%         25.000000
max       1423.000000
Name: Sum, dtype: float64

In [126]:
summary_stats["Sum"].median()

9.0

In [140]:
match_counts = summary_stats.loc[[16428]].T
match_counts.columns = ['Sum']

In [142]:
match_counts.sort_values(by = ['Sum'], ascending=False)

                                Sum
memory                109218.000000
cognition              87655.000000
dementia               51034.000000
cerebral               45886.000000
cerebrovascular        36370.000000
cerebellar             26863.000000
alzheimer              20581.000000
cognitive impairment   20267.000000
moca                    9767.000000
neurocognitive          7711.000000
mci                     3889.000000
amnesia                 3695.000000
ad                      2673.000000
lewy                    2561.000000
mmse                    2134.000000
lbd                      224.000000
corticobasal             147.000000
pick's                    41.000000
Sum                       26.218408
Unnamed: 0                      NaN

In [147]:
match_counts = match_counts.drop(labels = ['Sum', 'Unnamed: 0'], axis = 0)

In [148]:
match_counts

                           Sum
dementia               51034.0
cognition              87655.0
memory                109218.0
mmse                    2134.0
moca                    9767.0
alzheimer              20581.0
cognitive impairment   20267.0
mci                     3889.0
cerebellar             26863.0
neurocognitive          7711.0
lewy                    2561.0
pick's                    41.0
corticobasal             147.0
cerebral               45886.0
cerebrovascular        36370.0
amnesia                 3695.0
ad                      2673.0
lbd                      224.0

In [149]:
match_counts.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\FINAL\match_counts.csv")

In [4]:
f1 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\APOE-SLAT\EDA\Getting_Data\Biobank_filtered_csv\file1.csv")

In [5]:
f2 = f1 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\APOE-SLAT\EDA\Getting_Data\Biobank_filtered_csv\file2.csv")

In [6]:
len(f1) + len(f2)

17370

In [177]:
empi = df[df["EMPI"].isin(df["EMPI"].unique().tolist())]

In [178]:
empi

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,...,merged_regex_match,padded_merged_row_location,padded_merged_regex_sent,padded_char_count,note_char_count,PCPID,EncounterEpicProviderID,pcp_flag,SpecialtyDSC,padded_regex_match
0,0,0,0,0.0,100000272,10040002098,Z6352398,3.076070e+09,2015-06-17 00:00:00.0000000,Office Visit,...,[' cerebral'],"(5457, 6251)",ked at HMS in the department of psychobiology ...,794,19217.0,NaN,1521494,0,NaN,['cerebral']
1,1,1,1,1.0,100000272,10040002098,Z6352398,3.076214e+09,2015-07-16 00:00:00.0000000,Office Visit,...,[' memory'],"(3248, 4044)",or lymphadenopathy. Chest: Clear to auscultati...,796,5850.0,NaN,1012865,0,NaN,['memory']
2,2,2,2,14.0,100000272,10040002098,Z6352398,3.242118e+09,2019-03-14 00:00:00.0000000,Office Visit,...,[' dementia'],"(8345, 9145)",ession alone in the meta-analysis. We discusse...,800,13298.0,1002888.0,1668416,0,NaN,['dementia']
3,3,3,3,15.0,100000272,10040002098,Z6352398,3.322836e+09,2020-12-04 00:00:00.0000000,Telemedicine - audio only,...,"[' moca', ' cognition', ' memory']","[(930, 1152), (4778, 4987), (5004, 5349)]",------- ing tylenol really accept for this we...,803,8711.0,1002888.0,1746848,0,NaN,"['cognition', 'memory', 'moca']"
4,4,4,4,20.0,100000272,10040002098,Z6352398,3.325561e+09,2020-09-18 00:00:00.0000000,Telemedicine - audio only,...,"[' cognition', ' memory']","[(5188, 5576), (5593, 5991)]",------- in is related to cancer. Reassuringly...,804,9145.0,1002888.0,1746848,0,NaN,"['cognition', 'memory']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279219,60817,60817,277874,NaN,113705759,10127549029,Z16320629,3.285425e+09,2020-04-28 00:00:00.0000000,Telemedicine - audio only,...,"[' memory', ' cognition', ' cerebral', ' cereb...","[(538, 547), (1626, 1635), (1844, 1853), (108,...","------- se ""she took a break"" and wants to dis...",1949,11314.0,1007065.0,1558180,0,NaN,"['cognition', 'memory', 'cerebellar', 'cerebral']"
279220,60818,60818,277883,NaN,113705759,10127549029,Z16320629,3.305416e+09,2020-09-22 00:00:00.0000000,Telemedicine - audio only,...,"[' memory', ' cognition', ' cerebral', ' cereb...","[(323, 332), (1411, 1420), (1629, 1638), (108,...","------- all of her medications, including asp...",1734,10113.0,1007065.0,1558180,0,NaN,"['cognition', 'memory', 'cerebellar', 'cerebral']"
279221,60819,60819,277896,NaN,113705759,10127549029,Z16320629,3.327430e+09,2021-01-25 00:00:00.0000000,Telemedicine,...,"[' cognition', ' cerebral', ' memory', ' cereb...","[(2816, 2824), (108, 117), (326, 335), (974, 9...","------- ? Patient, Chart, daughter Olga Mode o...",3009,12320.0,1007065.0,1558180,0,NaN,"['dementia', 'cognition', 'memory', 'mci', 'ce..."
279222,60820,60820,277912,NaN,113705759,10127549029,Z16320629,3.349755e+09,2021-04-20 00:00:00.0000000,Telemedicine,...,"[' cognition', ' cerebral', ' cognitive impair...","[(2103, 2111), (108, 117), (326, 335), (544, 5...","------- ? Patient, Chart, daughter Olga Mode o...",2835,11250.0,1007065.0,1558180,0,NaN,"['dementia', 'cognition', 'moca', 'cognitive i..."
279223,60834,60834,277961,NaN,113708529,10127577079,Z16323433,3.196619e+09,2018-04-16 00:00:00.0000000,Office Visit,...,[' cognition'],"[(532, 541)]","------- h muscle invasive bladder cancer, curr...",1112,7027.0,1122712.0,1111086,0,NaN,['cognition']

In [180]:
empi = empi.drop_duplicates(subset = 'EMPI', keep = 'first')

In [184]:
len(empi)

16428

In [7]:
dem = pd.concat([f1, f2])

In [9]:
len(dem["EMPI"].unique())

8685

In [189]:
ages = pd.merge(empi, dem, left_on = 'EMPI', right_on = 'EMPI', how = 'left')

In [193]:
ages

,Unnamed: 0_x,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,EMPI,MRN_x,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,...,Age,Language,Race,Marital_status,Religion,Is_a_veteran,Zip_code,Country,Vital_status,Date_Of_Death\n
0,0,0,0,0.0,100000272,10040002098,Z6352398,3.076070e+09,2015-06-17 00:00:00.0000000,Office Visit,...,87.0,English-ENGLISH,BLACK OR AFRICAN AMERICAN,Legally Separated-LEGALLY SEPARATED,Catholic-CATHOLIC,Yes,02130,United States-UNITED STATES,Not reported as deceased,\n
2,8,10,10,51.0,100000521,10022362031,Z6352614,3.055196e+09,2005-05-19 00:00:00.0000000,System Generated,...,89.0,English-ENGLISH,White-WHITE,Widowed-WIDOW,Protestant-PROTESTANT,No,01778,United States-UNITED STATES,Not reported as deceased,\n
4,14,17,17,70.0,100000623,151209,Z6352700,3.245775e+09,2019-04-07 00:00:00.0000000,Hospital Encounter,...,84.0,English-ENGLISH,White-WHITE,Single-SINGLE,Non-denominational-NON-DENOM,Yes,02205,United States-UNITED STATES,Not reported as deceased,\n
6,19,23,23,93.0,100000894,200766,Z6352922,3.104652e+09,2016-01-17 00:00:00.0000000,Hospital Encounter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,26,32,32,107.0,100000920,204859,Z6352946,3.125179e+09,2016-07-19 00:00:00.0000000,Hospital Encounter,...,83.0,English-ENGLISH,BLACK OR AFRICAN AMERICAN,Widowed-WIDOW,Christian-CHRISTIAN,No,02130,United States-UNITED STATES,Date of Death reported from a Partners Hospital,04/26/2017\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23563,56325,56325,257269,NaN,112985226,6055785,Z15708552,3.154275e+09,2017-06-05 00:00:00.0000000,Office Visit,...,74.0,English-ENGLISH,White-WHITE,Married-MARRIED,Baptist-BAPTIST,No,03576,United States-UNITED STATES,Not reported as deceased,\n
23565,56348,56348,257359,NaN,112988049,6050342,Z15711478,3.154251e+09,2017-07-19 00:00:00.0000000,Office Visit,...,79.0,English-ENGLISH,White-WHITE,Widowed-WIDOW,Protestant-PROTESTANT,No,75248,United States-UNITED STATES,Not reported as deceased,\n
23567,57210,57210,261284,NaN,113093596,6092628,Z15769512,3.161991e+09,2017-07-17 00:00:00.0000000,Office Visit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23568,57904,57904,264052,NaN,113149962,6128251,Z15811708,3.164131e+09,2017-10-04 00:00:00.0000000,Office Visit,...,74.0,English-ENGLISH,White-WHITE,Married-MARRIED,Catholic-CATHOLIC,No,11590,United States-UNITED STATES,Not reported as deceased,\n
23570,58377,58377,268133,NaN,113205681,10122594137,Z15825165,3.166828e+09,2017-08-14 00:00:00.0000000,Office Visit,...,86.0,English-ENGLISH,White-WHITE,Married-MARRIED,Catholic-CATHOLIC,No,32907,United States-UNITED STATES,Not reported as deceased,\n

In [192]:
ages = ages.drop_duplicates(subset = 'EMPI', keep = 'first')

In [196]:
ages.columns

Index(['Unnamed: 0_x', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1',
       'EMPI', 'MRN_x', 'PatientID', 'PatientEncounterID', 'ContactDTS',
       'EncounterTypeDSC', 'NoteID', 'InpatientNoteTypeDSC', 'buckets',
       'NoteCSNID', 'LineNBR', 'NoteTXT', 'regex_location', 'regex_sent',
       'regex_match', 'match_count', 'pruned_regex_location',
       'merged_row_location', 'merged_regex_sent', 'merged_regex_match',
       'padded_merged_row_location', 'padded_merged_regex_sent',
       'padded_char_count', 'note_char_count', 'PCPID',
       'EncounterEpicProviderID', 'pcp_flag', 'SpecialtyDSC',
       'padded_regex_match', 'Unnamed: 0_y', 'EPIC_PMRN', 'MRN_Type', 'MRN_y',
       'Gender', 'Date_of_Birth', 'Age', 'Language', 'Race', 'Marital_status',
       'Religion', 'Is_a_veteran', 'Zip_code', 'Country', 'Vital_status',
       'Date_Of_Death\n'],
      dtype='object')

In [200]:
sum(ages["Race"].value_counts().values.tolist())

7144

In [ ]:
White-WHITE                                           6483
BLACK OR AFRICAN AMERICAN                              248
Other-OTHER                                            134
Not Recorded-DECLINED                                   75
Asian-ASIAN                                             67
Hispanic-HISPANIC OR LATINO                             53
Not Recorded-UNKNOWN                                    29
Not Recorded-@                                          20
Hispanic-OTHER@HISPANIC                                 18
Hispanic White-WHITE@HISPANIC                            5
American Indian-AMERICAN INDIAN OR ALASKA NATIVE         4
Hawaiian-NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER       3
Asian-ASIAN@HISPANIC                                     1
White-W                                                  1
Hispanic-@HISPANIC                                       1
Hispanic Black-BLACK OR AFRICAN AMERICAN@HISPANIC        1
Hispanic-HISPANIC OR LATINO@HISPANIC                     1

In [10]:
dem1 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\BioBank\sd587_03212118253982866_6375194824947826181_Dem.csv")
dem2 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\BioBank\sd587_03212118253982866_6375194824947826182_Dem.csv")

In [11]:
whole = pd.concat([dem1, dem2])
whole.head()

,EMPI,EPIC_PMRN,MRN_Type,MRN,Gender,Date_of_Birth,Age,Language,Race,Marital_status,Religion,Is_a_veteran,Zip_code,Country,Vital_status,Date_Of_Death\n
0,100093996,1.002347e+10,"PMRN, MGH, BWH, NWH, MEE","10023471500, 2269408, 04235107, 00069879, 7069459",Female,5/16/1954,66,English-ENGLISH,White-WHITE,Married-MARRIED,Lutheran-LUTHERAN,No,2493,United States-UNITED STATES,Not reported as deceased,\n
1,100094956,1.004417e+10,"PMRN, MGH, BWH, NWH, MEE","10044168093, 2990241, 04258836, 11072100, 1059154",Male,6/6/1961,59,English-ENGLISH,White-WHITE,Single-SINGLE,Catholic-CATHOLIC,No,2150,United States-UNITED STATES,Not reported as deceased,\n
2,100094940,1.004417e+10,"PMRN, MGH, BWH, FH, MEE","10044167335, 1104181, 40233769, 10255943, 1276075",Male,11/24/1954,66,English-ENGLISH,White-WHITE,Single-SINGLE,Catholic-CATHOLIC,No,2118,United States-UNITED STATES,Not reported as deceased,\n
3,100098036,1.004434e+10,"PMRN, MGH, BWH, FH, SRH, NWH, NSM, MEE, DFC","10044342664, 1127492, 30280366, 10321842, 0003...",Male,11/15/1931,89,English-ENGLISH,White-WHITE,Married-MARRIED,Catholic-CATHOLIC,Yes,2151,United States-UNITED STATES,Not reported as deceased,\n
4,100096100,1.004423e+10,"PMRN, MGH, BWH, FH, MEE","10044233715, 6306789, 04288601, 01264168, 1081763",Female,7/16/1965,55,English-ENGLISH,Not Recorded-DECLINED,Single-SINGLE,Christian-CHRISTIAN,No,2121,United States-UNITED STATES,Not reported as deceased,\n

In [12]:
len(whole["EMPI"].unique())

37795

In [13]:
patients = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\APOE-SLAT\nlp_annotator-dev\app\load_data\SLAT_production_7_24.csv")

In [14]:
demographics = pd.DataFrame()

In [15]:
race = []
for p in patients["EMPI"].unique():
    race.append(whole[whole["EMPI"] == p]["Race"].values)

In [17]:
demographics["race"] = race
demographics["empi"] = patients["EMPI"].unique()

In [19]:
demographics["race"].value_counts()

TypeError: unhashable type: 'numpy.ndarray'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 4588, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'numpy.ndarray'

[White-WHITE]                                           14895
[BLACK OR AFRICAN AMERICAN]                               570
[Other-OTHER]                                             304
[Not Recorded-DECLINED]                                   181
[Asian-ASIAN]                                             167
[Hispanic-HISPANIC OR LATINO]                             109
[Not Recorded-UNKNOWN]                                     73
[Not Recorded-@]                                           50
[Hispanic-OTHER@HISPANIC]                                  40
[Hispanic White-WHITE@HISPANIC]                            14
[American Indian-AMERICAN INDIAN OR ALASKA NATIVE]         12
[Hawaiian-NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER]        4
[Hispanic-@HISPANIC]                                        2
[Hispanic Black-BLACK OR AFRICAN AMERICAN@HISPANIC]         2
[Hispanic-HISPANIC OR LATINO@HISPANIC]                      2
[Asian-ASIAN@HISPANIC]                                      1
[White-W]                                                   1
[Hispanic-DECLINED@HISPANIC]                                1
Name: race, dtype: int64

In [20]:
sum(demographics["race"].value_counts())

16428

In [21]:
109+40+14+2+2+2+1

170

In [ ]:

[Not Recorded-UNKNOWN]                                     73
[White-W]                                                   1