In [1]:
import pandas as pd
import pandas.io.sql as psql
import os
import sys
from datetime import date
current_date = date.today()
#%load_ext autotime
import re
import csv
import pandas as pd
import numpy as np
import os
from glob import glob
from tqdm import tqdm
import matplotlib.pyplot as plt
#from matplotlib_venn import venn2, venn3
import warnings
import time
import datetime as dt
import itertools
from more_itertools import unique_everseen
warnings.filterwarnings("ignore")
#import pandasql as ps
import seaborn as sns
import json
from ast import literal_eval
import ast

In [2]:
total = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\total_summary_stats_updated_7_6_2021.csv")

In [3]:
total

       Unnamed: 0  Unnamed: 0.1       EMPI  Unique_Encounters
0               0             0  100000272                 10
1               1             1  100000521                  6
2               2             2  100000623                  5
3               3             3  100000894                  7
4               4             4  100000920                  3
...           ...           ...        ...                ...
16956        3913          3913  113714475                  7
16957        3914          3914  113716850                  4
16958        3915          3915  113722466                  5
16959        3916          3916  113722742                 12
16960        3917          3917  113727131                  1

[16961 rows x 4 columns]

In [9]:
one = total[total["Unique_Encounters"] == 1]
head_100 = one[:100]

In [11]:
m1 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\1\apoe_1_matches_updated_pruned.csv")
m2 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\2\apoe_2_matches_updated_pruned.csv")
m3 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\3\apoe_3_matches_updated_pruned.csv")
m4 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\4\apoe_4_matches_updated_pruned.csv")
m5 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\5\apoe_5_matches_updated_pruned.csv")

In [13]:
frames = [m1, m2, m3, m4, m5]
merged = pd.concat(frames)

In [22]:
merged[merged['EMPI'] == 100009747]

,Unnamed: 0,Unnamed: 0.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,InpatientNoteTypeDSC,...,NoteCSNID,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent
1314,5257,5257.0,100009747,3919528,Z6360516,3.283811e+09,2019-12-06 00:00:00.0000000,Hospital Encounter,3341615619,ED Provider Notes,...,3.322521e+09,1.0,----------------------------------------------...,"[(7209, 7219), (8892, 8901)]","'story of trauma, doubt subdural or epidural h...",['cerebellar'],1,"[(100, 111)]","[(7109, 7319), (8792, 9001)]","------- story of trauma, doubt subdural or epi..."

In [17]:
merged_2 = pd.merge(head_100, merged, left_on='EMPI', right_on='EMPI', how='left')
merged_2

,Unnamed: 0_x,Unnamed: 0.1_x,EMPI,Unique_Encounters,Unnamed: 0_y,Unnamed: 0.1_y,MRN,PatientID,PatientEncounterID,ContactDTS,...,NoteCSNID,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent
0,50,50,100009747,1,5257,5257.0,3919528,Z6360516,3.283811e+09,2019-12-06 00:00:00.0000000,...,3.322521e+09,1.0,----------------------------------------------...,"[(7209, 7219), (8892, 8901)]","'story of trauma, doubt subdural or epidural h...",['cerebellar'],1,"[(100, 111)]","[(7109, 7319), (8792, 9001)]","------- story of trauma, doubt subdural or epi..."
1,55,55,100010042,1,5524,5524.0,1283829,Z6360772,3.189350e+09,2018-02-09 00:00:00.0000000,...,1.881928e+09,1.0,----------------------------------------------...,"[(2648, 2657), (2732, 2738)]",'ent/Devices at home: Equipment/Devices Home E...,"['Cognition', 'Memory']",2,"[(100, 110)]","[(2548, 2838)]",------- ent/Devices at home: Equipment/Devices...
2,55,55,100010042,1,5528,5528.0,1283829,Z6360772,3.189350e+09,2018-02-09 00:00:00.0000000,...,1.884575e+09,1.0,----------------------------------------------...,"[(14061, 14070)]","'ilex . Able to SLR, +SILT to DP. 5/5 Strength...",['Cognition'],1,"[(100, 110)]","[(13961, 14170)]","------- ilex . Able to SLR, +SILT to DP. 5/5 S..."
3,59,59,100010311,1,5743,5743.0,1306653,Z6361001,3.130303e+09,2016-09-09 00:00:00.0000000,...,1.174440e+09,1.0,----------------------------------------------...,"[(13789, 13798)]",'ies: Extremities well perfused. No edema. Neu...,['Cognition'],1,"[(100, 110)]","[(13689, 13898)]",------- ies: Extremities well perfused. No ede...
4,154,154,100023305,1,16079,16079.0,2081156,Z6378486,3.155411e+09,2017-06-02 00:00:00.0000000,...,1.484424e+09,1.0,----------------------------------------------...,"[(2566, 2572)]",'edications this morning but not her cholester...,['memory'],1,"[(100, 107)]","[(2466, 2672)]",------- edications this morning but not her ch...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,1386,1386,100147829,1,145342,145342.0,10047180814,Z7062553,3.258588e+09,2019-07-02 00:00:00.0000000,...,2.708748e+09,1.0,----------------------------------------------...,"[(11041, 11050)]",'rmer JP site c/d/i GU: Urine draining light p...,['Cognition'],1,"[(100, 110)]","[(10941, 11150)]",------- rmer JP site c/d/i GU: Urine draining ...
133,1421,1421,100151713,1,149746,149746.0,5425582,Z7091487,3.045500e+09,2012-10-10 00:00:00.0000000,...,3.104455e+08,1.0,----------------------------------------------...,"[(8988, 8996)]",'r elevator to be passed between the implant a...,['cortical'],1,"[(100, 109)]","[(8888, 9096)]",------- r elevator to be passed between the im...
134,1438,1438,100153783,1,151607,151607.0,137543,Z7107122,3.245480e+09,2019-04-22 00:00:00.0000000,...,2.394850e+09,1.0,----------------------------------------------...,"[(3998, 4006)]",' mm distal right ureteral calculus. 2. 5 mm r...,['cortical'],1,"[(100, 109)]","[(3898, 4106)]",------- mm distal right ureteral calculus. 2....
135,1442,1442,100154138,1,151828,151828.0,10022816200,Z7109825,3.295259e+09,2020-02-17 00:00:00.0000000,...,3.724839e+09,1.0,----------------------------------------------...,"[(11814, 11823)]","' intact, moving all extremities Psych: calm m...",['Cognition'],1,"[(100, 110)]","[(11714, 11923)]","------- intact, moving all extremities Psych:..."
136,1456,1456,100155399,1,152985,152985.0,10047609036,Z7119207,3.048083e+09,2001-08-15 00:00:00.0000000,...,3.161108e+08,1.0,----------------------------------------------...,"[(1480, 1488)]","'d divide and conquer technique, the nuclear m...",['cortical'],1,"[(100, 109)]","[(1380, 1588)]","------- d divide and conquer technique, the nu..."

In [19]:
merged_2["NoteID"].nunique() #137 is b/c of multiple notes per encounter

137

In [20]:
merged_2.columns

Index(['Unnamed: 0_x', 'Unnamed: 0.1_x', 'EMPI', 'Unique_Encounters',
       'Unnamed: 0_y', 'Unnamed: 0.1_y', 'MRN', 'PatientID',
       'PatientEncounterID', 'ContactDTS', 'EncounterTypeDSC', 'NoteID',
       'InpatientNoteTypeDSC', 'buckets', 'NoteCSNID', 'LineNBR', 'NoteTXT',
       'regex_location', 'regex_sent', 'regex_match', 'match_count',
       'pruned_regex_location', 'merged_row_location', 'merged_regex_sent'],
      dtype='object')

In [24]:
merged_2.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\100_patients_verification.csv")

In [ ]:
113676821 113678823 113681718

In [25]:
merged[merged['EMPI'] == 113676821] #suppoed to have 2 unique encounter ids

,Unnamed: 0,Unnamed: 0.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,InpatientNoteTypeDSC,...,NoteCSNID,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent
60534,277014,NaN,113676821,10127255791,Z16291324,3.187025e+09,2018-02-06 00:00:00.0000000,Office Visit,1851722182,Progress Notes,...,1.807318e+09,1.0,----------------------------------------------...,"[(5255, 5261), (6069, 6079)]","""alert, attentive, and oriented x 3. Speech is...","[""Memory""]",1,"[(97, 104)]","[(5155, 5361), (5969, 6179)]","------- is alert, attentive, and oriented x 3...."
60535,277016,NaN,113676821,10127255791,Z16291324,3.188836e+09,2018-02-27 00:00:00.0000000,Office Visit,1878506152,Progress Notes,...,1.834913e+09,1.0,----------------------------------------------...,"[(8397, 8403), (9209, 9219)]","""alert, attentive, and oriented x 3. Speech is...","[""Memory""]",1,"[(97, 104)]","[(8297, 8503), (9109, 9319)]","------- is alert, attentive, and oriented x 3...."

In [26]:
merged[merged['EMPI'] == 113678823] #suppoed to have 3 unique encounter ids

,Unnamed: 0,Unnamed: 0.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,InpatientNoteTypeDSC,...,NoteCSNID,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent
60536,277018,NaN,113678823,6260013,Z16293330,3.187727e+09,2018-01-29 00:00:00.0000000,Hospital Encounter,1878616721,Discharge Summary,...,1.833265e+09,1.0,----------------------------------------------...,"[(12220, 12229)]","""soft, ND, ATTP; incision C/D/I GU: foley drai...","[""Cognition""]",1,"[(94, 104)]","[(12120, 12329)]","------- omen: soft, ND, ATTP; incision C/D/I G..."
60537,277020,NaN,113678823,6260013,Z16293330,3.203611e+09,2018-07-20 00:00:00.0000000,Office Visit,2064564590,Progress Notes,...,2.024623e+09,1.0,----------------------------------------------...,"[(6412, 6420)]","""Four (4) hilar lymph nodes are negative for m...","[""cortical""]",1,"[(96, 105)]","[(6312, 6520)]",------- at. Four (4) hilar lymph nodes are neg...
60538,277027,NaN,113678823,6260013,Z16293330,3.361089e+09,2021-03-22 00:00:00.0000000,Hospital Encounter,5630935490,Discharge Summary,...,5.627199e+09,1.0,----------------------------------------------...,"[(8034, 8043)]","""Exam Significant Discharge Exam Findings: See...","[""Cognition""]",1,"[(93, 103)]","[(7934, 8143)]",------- charge Exam Significant Discharge Exam...

In [27]:
merged[merged['EMPI'] == 113681718] #suppoed to have 3 unique encounter ids

,Unnamed: 0,Unnamed: 0.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,InpatientNoteTypeDSC,...,NoteCSNID,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent
60539,277030,NaN,113681718,10127305273,Z16296267,3.098939e+09,2015-12-15 00:00:00.0000000,Office Visit,724171123,Progress Notes,...,6.949376e+08,1.0,----------------------------------------------...,"[(910, 918)]","""that she has been doing well, but is tired du...","[""dementia""]",1,"[(99, 108)]","[(810, 1018)]","------- that she has been doing well, but is ..."
60540,277033,NaN,113681718,10127305273,Z16296267,3.184374e+09,2018-07-03 00:00:00.0000000,Office Visit,2042391177,Progress Notes,...,2.001793e+09,1.0,----------------------------------------------...,"[(1751, 1759)]","""Angela has been stressed, and her PCP added L...","[""dementia""]",1,"[(99, 108)]","[(1651, 1859)]","------- Angela has been stressed, and her PCP..."
60541,277039,NaN,113681718,10127305273,Z16296267,3.356283e+09,2021-03-17 00:00:00.0000000,Office Visit,5446039114,Progress Notes,...,5.440928e+09,1.0,----------------------------------------------...,"[(778, 784), (1989, 1997), (6085, 6091)]","""s/p DCCV on 10/2/2017, 10/2020 subacute right...","[""memory""]",1,"[(96, 103)]","[(678, 884), (1889, 2097), (5985, 6191)]","------- on, s/p DCCV on 10/2/2017, 10/2020 sub..."