In [1]:
import pandas as pd
import pandas.io.sql as psql
import os
import sys
from datetime import date
current_date = date.today()
#%load_ext autotime
import re
import csv
import pandas as pd
import numpy as np
import os
from glob import glob
from tqdm import tqdm
import matplotlib.pyplot as plt
#from matplotlib_venn import venn2, venn3
import warnings
import time
import datetime as dt
import itertools
from more_itertools import unique_everseen
warnings.filterwarnings("ignore")
#import pandasql as ps
import seaborn as sns
import json
from ast import literal_eval
import ast

In [2]:
total = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\total_summary_stats_updated_7_6_2021.csv")

In [3]:
total

       Unnamed: 0  Unnamed: 0.1       EMPI  Unique_Encounters
0               0             0  100000272                 10
1               1             1  100000521                  6
2               2             2  100000623                  5
3               3             3  100000894                  7
4               4             4  100000920                  3
...           ...           ...        ...                ...
16956        3913          3913  113714475                  7
16957        3914          3914  113716850                  4
16958        3915          3915  113722466                  5
16959        3916          3916  113722742                 12
16960        3917          3917  113727131                  1

[16961 rows x 4 columns]

In [4]:
one = total[total["Unique_Encounters"] == 1]
head_100 = one[:100]

In [6]:
m1 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\1\apoe_1_matches_complete.csv")
m2 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\2\apoe_2_matches_complete.csv")
m3 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\3\apoe_3_matches_complete.csv")
m4 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\4\apoe_4_matches_complete.csv")
m5 = pd.read_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\5\apoe_5_matches_complete.csv")

In [141]:
len(m1), len(m2), len(m3), len(m4), len(m5)

(62617, 57029, 57957, 60480, 60871)

In [7]:
frames = [m1, m2, m3, m4, m5]
merged = pd.concat(frames)

In [8]:
merged[merged['EMPI'] == 100009747]

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
1314,1314,5257,5257.0,100009747,3919528,Z6360516,3.283811e+09,2019-12-06 00:00:00.0000000,Hospital Encounter,3341615619,...,1.0,----------------------------------------------...,"[(7209, 7219), (8892, 8901)]","'story of trauma, doubt subdural or epidural h...",['cerebellar'],1,"[(100, 111)]","[(7109, 7319), (8792, 9001)]","------- story of trauma, doubt subdural or epi...",[' cerebellar']

In [37]:
merged_2 = pd.merge(head_100, merged, left_on='EMPI', right_on='EMPI', how='left')
merged_2.head(90)

,Unnamed: 0_x,Unnamed: 0.1_x,EMPI,Unique_Encounters,Unnamed: 0_y,Unnamed: 0.1_y,Unnamed: 0.1.1,MRN,PatientID,PatientEncounterID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
0,50,50,100009747,1,1314,5257,5257.0,3919528,Z6360516,3.283811e+09,...,1.0,----------------------------------------------...,"[(7209, 7219), (8892, 8901)]","'story of trauma, doubt subdural or epidural h...",['cerebellar'],1,"[(100, 111)]","[(7109, 7319), (8792, 9001)]","------- story of trauma, doubt subdural or epi...",[' cerebellar']
1,55,55,100010042,1,1384,5524,5524.0,1283829,Z6360772,3.189350e+09,...,1.0,----------------------------------------------...,"[(2648, 2657), (2732, 2738)]",'ent/Devices at home: Equipment/Devices Home E...,"['Cognition', 'Memory']",2,"[(100, 110)]","[(2548, 2838)]",------- ent/Devices at home: Equipment/Devices...,[' cognition']
2,55,55,100010042,1,1385,5528,5528.0,1283829,Z6360772,3.189350e+09,...,1.0,----------------------------------------------...,"[(14061, 14070)]","'ilex . Able to SLR, +SILT to DP. 5/5 Strength...",['Cognition'],1,"[(100, 110)]","[(13961, 14170)]","------- ilex . Able to SLR, +SILT to DP. 5/5 S...",[' cognition']
3,59,59,100010311,1,1443,5743,5743.0,1306653,Z6361001,3.130303e+09,...,1.0,----------------------------------------------...,"[(13789, 13798)]",'ies: Extremities well perfused. No edema. Neu...,['Cognition'],1,"[(100, 110)]","[(13689, 13898)]",------- ies: Extremities well perfused. No ede...,[' cognition']
4,154,154,100023305,1,3959,16079,16079.0,2081156,Z6378486,3.155411e+09,...,1.0,----------------------------------------------...,"[(2566, 2572)]",'edications this morning but not her cholester...,['memory'],1,"[(100, 107)]","[(2466, 2672)]",------- edications this morning but not her ch...,[' memory']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,1036,1036,100114922,1,26225,111925,111925.0,1271064,Z6814271,3.276136e+09,...,1.0,----------------------------------------------...,"[(35852, 35861)]","'ble DP pulse, warm and well-perfused Dressing...",['Cognition'],1,"[(100, 110)]","[(35752, 35961)]","------- ble DP pulse, warm and well-perfused D...",[' cognition']
86,1046,1046,100115771,1,26521,113059,113059.0,10233253,Z6820663,3.254196e+09,...,1.0,----------------------------------------------...,"[(4043, 4052)]",'ly normal coordination and gait. Psych: Alert...,['cognition'],1,"[(100, 110)]","[(3943, 4152)]",------- ly normal coordination and gait. Psych...,[' cognition']
87,1052,1052,100116561,1,26623,113413,113413.0,10045405916,Z6826676,3.050010e+09,...,1.0,----------------------------------------------...,"[(902, 917), (3227, 3242)]",'LIZATION AND SIGNIFICANT FINDINGS CC: 91 yo w...,['cerebrovascular'],1,"[(100, 116)]","[(802, 1017), (3127, 3342)]",------- LIZATION AND SIGNIFICANT FINDINGS CC: ...,[' cerebrovascular']
88,1079,1079,100119622,1,27264,116393,116393.0,1318935,Z6849673,3.233873e+09,...,1.0,----------------------------------------------...,"[(518, 527)]",'Cognitive Restructuring Skills Intervention: ...,['cognition'],1,"[(100, 110)]","[(418, 627)]",------- Cognitive Restructuring Skills Interve...,[' cognition']
89,1084,1084,100119952,1,27322,116557,116557.0,2716307,Z6852084,3.051314e+09,...,1.0,----------------------------------------------...,"[(4303, 4309), (5664, 5674), (9846, 9852)]",'phasic errors; Follows 1-part and 2-part comm...,['Memory'],1,"[(100, 107)]","[(4203, 4409), (5564, 5774), (9746, 9952)]",------- phasic errors; Follows 1-part and 2-pa...,"[' memory', ' cerebellar']"

In [11]:
merged_2["NoteID"].nunique() #137 is b/c of multiple notes per encounter

137

In [12]:
merged_2.columns

Index(['Unnamed: 0_x', 'Unnamed: 0.1_x', 'EMPI', 'Unique_Encounters',
       'Unnamed: 0_y', 'Unnamed: 0.1_y', 'Unnamed: 0.1.1', 'MRN', 'PatientID',
       'PatientEncounterID', 'ContactDTS', 'EncounterTypeDSC', 'NoteID',
       'InpatientNoteTypeDSC', 'buckets', 'NoteCSNID', 'LineNBR', 'NoteTXT',
       'regex_location', 'regex_sent', 'regex_match', 'match_count',
       'pruned_regex_location', 'merged_row_location', 'merged_regex_sent',
       'merged_regex_match'],
      dtype='object')

In [127]:
merged_2.to_excel(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\100_patients_verification_3.xlsx")

In [128]:
merged_2.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\100_patients_verification_3.csv")

In [ ]:
113676821 113678823 113681718

In [14]:
merged[merged['EMPI'] == 113676821] #suppoed to have 2 unique encounter ids

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
60534,60534,277014,NaN,113676821,10127255791,Z16291324,3.187025e+09,2018-02-06 00:00:00.0000000,Office Visit,1851722182,...,1.0,----------------------------------------------...,"[(5255, 5261), (6069, 6079)]","""alert, attentive, and oriented x 3. Speech is...","[""Memory""]",1,"[(97, 104)]","[(5155, 5361), (5969, 6179)]","------- is alert, attentive, and oriented x 3....","[' memory', ' cerebellar']"
60535,60535,277016,NaN,113676821,10127255791,Z16291324,3.188836e+09,2018-02-27 00:00:00.0000000,Office Visit,1878506152,...,1.0,----------------------------------------------...,"[(8397, 8403), (9209, 9219)]","""alert, attentive, and oriented x 3. Speech is...","[""Memory""]",1,"[(97, 104)]","[(8297, 8503), (9109, 9319)]","------- is alert, attentive, and oriented x 3....","[' memory', ' cerebellar']"

In [15]:
merged[merged['EMPI'] == 113678823] #suppoed to have 3 unique encounter ids

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
60536,60536,277018,NaN,113678823,6260013,Z16293330,3.187727e+09,2018-01-29 00:00:00.0000000,Hospital Encounter,1878616721,...,1.0,----------------------------------------------...,"[(12220, 12229)]","""soft, ND, ATTP; incision C/D/I GU: foley drai...","[""Cognition""]",1,"[(94, 104)]","[(12120, 12329)]","------- omen: soft, ND, ATTP; incision C/D/I G...",[' cognition']
60537,60537,277020,NaN,113678823,6260013,Z16293330,3.203611e+09,2018-07-20 00:00:00.0000000,Office Visit,2064564590,...,1.0,----------------------------------------------...,"[(6412, 6420)]","""Four (4) hilar lymph nodes are negative for m...","[""cortical""]",1,"[(96, 105)]","[(6312, 6520)]",------- at. Four (4) hilar lymph nodes are neg...,[' cortical']
60538,60538,277027,NaN,113678823,6260013,Z16293330,3.361089e+09,2021-03-22 00:00:00.0000000,Hospital Encounter,5630935490,...,1.0,----------------------------------------------...,"[(8034, 8043)]","""Exam Significant Discharge Exam Findings: See...","[""Cognition""]",1,"[(93, 103)]","[(7934, 8143)]",------- charge Exam Significant Discharge Exam...,[' cognition']

In [16]:
merged[merged['EMPI'] == 113681718] #suppoed to have 3 unique encounter ids

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,EMPI,MRN,PatientID,PatientEncounterID,ContactDTS,EncounterTypeDSC,NoteID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
60539,60539,277030,NaN,113681718,10127305273,Z16296267,3.098939e+09,2015-12-15 00:00:00.0000000,Office Visit,724171123,...,1.0,----------------------------------------------...,"[(910, 918)]","""that she has been doing well, but is tired du...","[""dementia""]",1,"[(99, 108)]","[(810, 1018)]","------- that she has been doing well, but is ...",[' dementia']
60540,60540,277033,NaN,113681718,10127305273,Z16296267,3.184374e+09,2018-07-03 00:00:00.0000000,Office Visit,2042391177,...,1.0,----------------------------------------------...,"[(1751, 1759)]","""Angela has been stressed, and her PCP added L...","[""dementia""]",1,"[(99, 108)]","[(1651, 1859)]","------- Angela has been stressed, and her PCP...",[' dementia']
60541,60541,277039,NaN,113681718,10127305273,Z16296267,3.356283e+09,2021-03-17 00:00:00.0000000,Office Visit,5446039114,...,1.0,----------------------------------------------...,"[(778, 784), (1989, 1997), (6085, 6091)]","""s/p DCCV on 10/2/2017, 10/2020 subacute right...","[""memory""]",1,"[(96, 103)]","[(678, 884), (1889, 2097), (5985, 6191)]","------- on, s/p DCCV on 10/2/2017, 10/2020 sub...","[' dementia', ' memory']"

In [133]:
unique_ids = merged_2["PatientID"]
unique_ids = list(unique_ids)
len(unique_ids)

137

In [18]:
merged_2[merged_2['PatientID'] == unique_ids[1]]

,Unnamed: 0_x,Unnamed: 0.1_x,EMPI,Unique_Encounters,Unnamed: 0_y,Unnamed: 0.1_y,Unnamed: 0.1.1,MRN,PatientID,PatientEncounterID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
1,55,55,100010042,1,1384,5524,5524.0,1283829,Z6360772,3.189350e+09,...,1.0,----------------------------------------------...,"[(2648, 2657), (2732, 2738)]",'ent/Devices at home: Equipment/Devices Home E...,"['Cognition', 'Memory']",2,"[(100, 110)]","[(2548, 2838)]",------- ent/Devices at home: Equipment/Devices...,[' cognition']
2,55,55,100010042,1,1385,5528,5528.0,1283829,Z6360772,3.189350e+09,...,1.0,----------------------------------------------...,"[(14061, 14070)]","'ilex . Able to SLR, +SILT to DP. 5/5 Strength...",['Cognition'],1,"[(100, 110)]","[(13961, 14170)]","------- ilex . Able to SLR, +SILT to DP. 5/5 S...",[' cognition']

In [132]:
# 100010311
merged_2[merged_2['PatientID'] == unique_ids[2]]

,Unnamed: 0_x,Unnamed: 0.1_x,EMPI,Unique_Encounters,Unnamed: 0_y,Unnamed: 0.1_y,Unnamed: 0.1.1,MRN,PatientID,PatientEncounterID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
3,59,59,100010311,1,1443,5743,5743.0,1306653,Z6361001,3.130303e+09,...,1.0,----------------------------------------------...,"[(13789, 13798)]",'ies: Extremities well perfused. No edema. Neu...,['Cognition'],1,"[(100, 110)]","[(13689, 13898)]",------- ies: Extremities well perfused. No ede...,[' cognition']

In [42]:
merged_2.loc[[85]]

,Unnamed: 0_x,Unnamed: 0.1_x,EMPI,Unique_Encounters,Unnamed: 0_y,Unnamed: 0.1_y,Unnamed: 0.1.1,MRN,PatientID,PatientEncounterID,...,LineNBR,NoteTXT,regex_location,regex_sent,regex_match,match_count,pruned_regex_location,merged_row_location,merged_regex_sent,merged_regex_match
85,1036,1036,100114922,1,26225,111925,111925.0,1271064,Z6814271,3.276136e+09,...,1.0,----------------------------------------------...,"[(35852, 35861)]","'ble DP pulse, warm and well-perfused Dressing...",['Cognition'],1,"[(100, 110)]","[(35752, 35961)]","------- ble DP pulse, warm and well-perfused D...",[' cognition']

In [134]:
cols =  [' dementia', ' cognition', ' memory', ' cdr', ' mmse', ' moca', ' alzheimer', ' cognitive impairment', ' mci', ' cerebellar', ' neurocognitive', ' lewy', " pick's", ' cortical', ' corticobasal', ' cerebral', ' cerebrovascular', ' amnesia']
summary_stats  = pd.DataFrame(pd.np.empty((len(unique_ids), len(cols))) * pd.np.nan) 
summary_stats.columns = cols

In [135]:
summary_stats

,dementia,cognition,memory,cdr,mmse,moca,alzheimer,cognitive impairment,mci,cerebellar,neurocognitive,lewy,pick's,cortical,corticobasal,cerebral,cerebrovascular,amnesia
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
for i in (range(len(unique_ids))):
    keyword_list = list(set(merged_2[merged_2['PatientID'] == unique_ids[i]]['merged_regex_match'].values))
    #print("KL: ", keyword_list)
    match_tuples = []
    for j in range(len(keyword_list)):
        sub = "\', \'"
        x = keyword_list[j][2:len(keyword_list[j])-2]
        #print("X: ", x)
        if sub in x:
            #print("YES")
            x = x.split("\', \'")
            #print("X2: ", x)
        else:
            x = x.split("\", \"")
        for z in range(len(x)):
            match_tuples.append((x[z], 0))
    #print("MT: ", match_tuples)

    freq = {" dementia":0
        ," cognition":0
        ," cognition":0
        ," memory":0
        ," cdr":0
        ," mmse":0
        ," moca":0
        ," alzheimer":0
        ,' cognitive impairment':0
        ," mci":0
        ," cerebellar":0
        ," neurocognitive":0
        ," lewy":0
        ," pick's":0
        ," cortical":0
        ," corticobasal":0
        ," cerebral":0
        ," cerebrovascular":0
        ," amnesia":0
    }

    for k, v in match_tuples:   
        if (k != ''):
            freq.update({str(k.lower()):int(freq[k.lower()] + 1)})
            
    #print(freq.items())
    #print(summary_stats["dementia"])
    for k, v in freq.items():
        #print(str(k.lower()))
        summary_stats[str(k.lower())][i] = int(v)

In [137]:
summary_stats

,dementia,cognition,memory,cdr,mmse,moca,alzheimer,cognitive impairment,mci,cerebellar,neurocognitive,lewy,pick's,cortical,corticobasal,cerebral,cerebrovascular,amnesia
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
135,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
136,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [140]:
summary_stats.to_csv(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\totals.csv")

In [142]:
totals = pd.read_excel(r"C:\Users\MIND_DS\Dropbox (Partners HealthCare)\NLP\Tanish\BigDataSets\Regex_match\100_patients_verification.xlsx", sheet_name = "Sheet1", index_col = 0)

In [145]:
len(totals["PatientEncounterID"].unique())

100

## Regex Pattern Tests

In [183]:
string = '-------MCI mci otocol: Ms. Rojas underwent a myocardial perfusion PET study following the IV administration of 4.5 mCi and 15.0 mCi of N-13 Ammonia at rest and during vasodilator stress, respectively. Gated myocardial perfusion'

pattern = re.compile(r'(?-i:)\bMCI\b|(?-i:)\bmci\b')

for match in re.finditer((pattern) , string):
    s = match.start()
    e = match.end()
    print ('String match "%s" at %d:%d' % (string[s:e], s, e))

String match "MCI" at 7:10
String match "mci" at 11:14

In [211]:
string2 = "------- ly normal coordination and gait. Psych: Alert and oriented for age, normal mood, affect, speech and COGNITION. See care plans and review of systems above for further history details. See associated Encounter"
pattern2 = re.compile(r'(?i)\bcognition\b')

for match in re.finditer((pattern2) , string2):
    s = match.start()
    e = match.end()
    print ('String match "%s" at %d:%d' % (string2[s:e], s, e))

String match "COGNITION" at 108:117